### ISSUE TITLE
Make this citable

### ISSUE THREAD

**Issue by DiegoDVillacreses** [benwhalley/just-enough-r#2]
This is an outstanding book. I suggest you make it citable by any means. I found two easy suggestions from GitHub:

- https://guides.github.com/activities/citable-code/
- https://github.com/AASJournals/Tutorials/blob/master/Repositories/CitingRepositories.m

**Comment by benwhalley** [comment]
Hey - that's really kind, thanks. I'd actually been meaning to do this, so it was a good prompt. The book now has a DOI via zenondo:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3666150.svg)](https://doi.org/10.5281/zenodo.3666150)

I'm very mindful there are typos, errors etc in the book and I need to do some work to polish it up for a proper release. Please feel free to file anything you spot as an issue here.
