### ISSUE TITLE
Code inside Book has errors

### ISSUE THREAD

**Issue by alapo** [benwhalley/just-enough-r#3]
Hi there,

Thank you very much for your valuable contribution, I refer your book to incoming students. I was curious if you had any difficulties running the code on lmer contrasts [here](https://benwhalley.github.io/just-enough-r/contrasts-lmer.html)

I tried running the code myself and I also get errors. The error occurs because `broom::tidy` does not produce confidence intervals.

```
m <- lmer(Reaction~factor(Days)+(1|Subject), data=lme4::sleepstudy)
anova(m)
m.emm <- emmeans::emmeans(m, "Days")
m.emm

m.emm.df <- m.emm %>% # this line causes the error
  broom::tidy()

m.emm.df %>%
  ggplot(aes(Days, estimate, ymin=conf.low, ymax=conf.high)) +
  geom_pointrange() +
  ylab("RT")
```

The console expectantly shows

```
Error in FUN(X[[i]], ...) : object 'conf.low' not found
```

**Comment by benwhalley** [comment]
Hi - glad to hear it's useful. I do sometimes feel like I ought to spend a bit of time tidying up and updating — there are some rough edges!

That said, that line does work for me. I wonder if it's a package version issue. This is what I'm running:

```
installed.packages() %>% as_tibble %>% filter(str_detect(Package, "tidyverse|broom|lmer|lme4")) %>% select(Package, Version) %>% pander::pander()

----------------------
   Package     Version 
------------- ---------
    broom       0.5.6  

 broom.mixed    0.2.6  

    lme4       1.1-23  

  lmerTest      3.1-2  

  tidyverse     1.3.0  
-----------------------
```


`requirements.R` does list all packages required, but I haven't got around to pinning versions or using packrat or MRAN for a snapshot date. I'll do that soon.

**Comment by alapo** [comment]
Hey!

Ya its tough to find a happy medium to get students started. Seems like the default arguments may have changed since you wrote your book since I do have different versions.

```
installed.packages() %>% as_tibble %>% filter(str_detect(Package, "tidyverse|broom|lmer|lme4")) %>% select(Package, Version) %>% pander::pander()

-----------------------
   Package     Version 
------------- ---------
    broom       0.7.1  

 broom.mixed    0.2.6  

 broomExtra     4.0.6  

    lme4       1.1-23  

  lmerTest      3.1-2  

  tidyverse     1.3.0  
-----------------------
```

I got the code submitted working by setting `conf.int = TRUE`

Complete code below

```
m <- lmer(Reaction~factor(Days)+(1|Subject), data=lme4::sleepstudy)
anova(m)
m.emm <- emmeans::emmeans(m, "Days")
m.emm

m.emm.df <- m.emm %>% 
  broom::tidy(conf.int = TRUE) # this line changed

m.emm.df %>%
  ggplot(aes(Days, estimate, ymin=conf.low, ymax=conf.high)) +
  geom_pointrange() +
  ylab("RT")
```
